server:
  port: 50000

dtu:
  deployment-type: ${SERVICE_DEPLOYMENT_TYPE:dev}

  environments:
    dev:
      vault-user: dtu
      vault-mount: dtu
      vault-url: http://localhost:9001
      datasources-url: http://localhost:9000/databases

    test:
      vault-user: dtu
      vault-mount: dtu
      vault-url: http://vault:8083
      datasources-url: http://contracts/databases

    prod:
      vault-role: k8srole
      vault-user: dtu
      vault-mount: dtu
      vault-url: http://vault-service.default.svc
      datasources-url: http://contracts/databases
      k8s-token-path: /var/run/secrets/kubernetes.io/serviceaccount/token