server:
  port: 9002

dtu:
  deployment-type: ${SERVICE_DEPLOYMENT_TYPE:dev}

  environments:
    dev:
      vault-user: dtu
      vault-mount: dtu
      vault-url: http://localhost:9001
      oauth-url: http://localhost:9000/contracts/oauth2
      datasources-url: http://localhost:9000/contracts/databases

    test:
      vault-user: dtu
      vault-mount: dtu
      vault-url: http://vault:8083
      oauth-url: http://registry/contracts/oauth2
      datasources-url: http://registry/contracts/databases

    prod:
      vault-role: k8srole
      vault-user: dtu
      vault-mount: dtu
      vault-url: http://vault-service.default.svc
      oauth-url: http://registry/contracts/oauth2
      datasources-url: http://registry/contracts/databases
      k8s-token-path: /var/run/secrets/kubernetes.io/serviceaccount/token